### ISSUE TITLE
Translation in 'how to use' modal

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/ng2-tools-page#102]
Looks weird in rtl language:

![selection_204](https://user-images.githubusercontent.com/18219232/31768357-b9fcc4c8-b4d7-11e7-8915-b55f545ae65b.png)

![selection_206](https://user-images.githubusercontent.com/18219232/31768419-0ca92752-b4d8-11e7-8c32-012d43dd866b.png)

**Comment by angieskazka** [comment]
this looks correct except for the missing translation )
