### ISSUE TITLE
Sometimes the same axes values gives different scaling of axes

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/ng2-tools-page#103]
![selection_197](https://user-images.githubusercontent.com/18219232/31768921-0c279de8-b4da-11e7-8786-ace6999c87f2.png)

Steps to reproduce:
1. Open Bubble chart
2. Choose 'Income' for y axis (assuming X-axis holds 'income' and Y-axis - 'Life Expectancy' by default )
Should the chart start from the bottom left corner?
Because if change x axis for something else and then back to 'Income' - it will be so

**Comment by angieskazka** [comment]
i know why it happens and it’s not a problem
