### ISSUE TITLE
Back/Forward in browser doesn't change language

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/ng2-tools-page#122]
Steps:
1. Open tools-page
2. Change language
3. Press 'back' in browser

Expected result:
The language should change back to default

Screenshot:
![ezgif com-video-to-gif 13](https://user-images.githubusercontent.com/18219232/31941803-cceced72-b8cb-11e7-8721-be3caa77a8c8.gif)

**Comment by angieskazka** [comment]
@buchslava looks like same reason as #54: empty state object not overriding what vizabi has

**Comment by angieskazka** [comment]
reopening temporarily because this needs to be fixed together with other issues and retested
