### ISSUE TITLE
bubble-map shows broken on Chrome when running locally

### ISSUE THREAD

**Issue by Rathunter** [Gapminder/ng2-tools-page#16]
Running this project locally by `npm start` and seeing the following result for bubble-map on Chrome Version 56.0.2924.87 (64-bit) running on Mac.
<img width="1378" alt="screen shot 2017-03-18 at 12 58 34 pm" src="https://cloud.githubusercontent.com/assets/2431857/24074410/46c1afde-0bde-11e7-86e0-737c2c2a28a4.png">

Console is showing the following error on that page..
<img width="1056" alt="screen shot 2017-03-18 at 1 01 54 pm" src="https://cloud.githubusercontent.com/assets/2431857/24074414/5ea22c3c-0bde-11e7-9a69-7910ed0bc16b.png">

**Comment by angieskazka** [comment]
fixed in 2fe6ef872f6b2e6b121af90423778925c2da2a70
