### ISSUE TITLE
Tools page layout and design improvements

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/ng2-tools-page#26]
1) Change the desktop layout to look more like we have on mobile now: first comes the stripe of other tools, then related items. Note the styling of headers and text labels of the tools

develop a way to pick a nice size and a nice number of thumbs in the ribbon. let size of thumbnails adapt to the screen size: no less than certain width, no bigger than certain width, fit a nice number of thumbs for all screen sizes. scroll to see the rest. 

![image](https://user-images.githubusercontent.com/3648190/29869189-45c4fee4-8d82-11e7-86f4-ebab59eebed2.png)

2) Note that there is "Dollar street" tool, which is basically a picture and a link to a different page

3) Note the footer with links to other places on Gapminder website (Angie: rename "Gapminder world" to "Old bubble chart" down there)

4) note how the top of tools should be peeking from below

![image](https://user-images.githubusercontent.com/3648190/29869380-0047826e-8d83-11e7-912c-dacf5c0b97ca.png)

5) Note the navigation breadcrumbs in the top. I'm not sure yet what to do when clicking "Tools". Will post here later once i get to hear more from ola

6) the video instruction link on top should open a popup, where an embedded video from Vimeo would play. https://vimeo.com/231885967

**Comment by buchslava** [comment]
I've provided next changes:

![screenshot from 2017-09-12 15-10-16](https://user-images.githubusercontent.com/6974213/30325515-b65ceb94-97cd-11e7-9a49-b5d10f0f54ed.png)

1. Header was modified: breadcrumbs and 'how to use' was added. As far as I understand breadcrumbs will be finished later.

Questions:
- now if you click on 'how to use' then an expected link will be opened in a separate window. Is inner pop-up expected? If yes tell me please what kind of a popup (placement, design...)
- regarding mobile menu (you can see it below): what should we do with the old menu ("FACTS TEACH ABOUT")? @angieskazka 

![screenshot from 2017-09-12 15-10-22](https://user-images.githubusercontent.com/6974213/30325519-bbc84128-97cd-11e7-907c-58c2f729f655.png)

2. footer was provided
@angieskazka give me please hrefs for new menu:

![screenshot from 2017-09-12 15-10-38](https://user-images.githubusercontent.com/6974213/30325523-bff84996-97cd-11e7-99cc-95698c0d3be1.png)
3. vizabi container height was fixed
