### ISSUE TITLE
Tools page can't find a JS resource on start sometimes

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/ng2-tools-page#27]
I have observed this behavior but it's not stable

![image](https://user-images.githubusercontent.com/3648190/29911026-a526798a-8e2c-11e7-8328-60531b8a3658.png)

![image](https://user-images.githubusercontent.com/3648190/29916366-d544167e-8e3e-11e7-821f-a0fe48079f73.png)

**Comment by buchslava** [comment]
All as I can propose in this case is an update for all packages especially `angular-cli`, because I see only two reasons:

1. angular-cli issue
2. unstable nginx on prod or deployment during your test

may I prepare updated package.json? @angieskazka

**Comment by angieskazka** [comment]
yes, go ahead @buchslava

**Comment by angieskazka** [comment]
issues still persists
