### ISSUE TITLE
Share buttons with prompts don't work on mobile

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/ng2-tools-page#76]
'plane' and 'iframe' buttons show the prompt with the link and it doesn't work on mobile. Clicking these buttons don't do anything.

Steps to reproduce:
1. Open tools-page on mobile
2. Open menu
3. Tap on 'plane' icon in sharing section

Expected result:
Sharing link appears

Current result:
Nothing happens

![selection_166](https://user-images.githubusercontent.com/18219232/31541944-e10d01f4-b018-11e7-84f5-b90628fb0794.png)

**Comment by angieskazka** [comment]
The plane should totally work: ideally copy the link to clipboard and "link copied to clipboard"
embed button we can hide on mobile

**Comment by angieskazka** [comment]
they do now
