### ISSUE TITLE
Starting with a clean URL results in errors

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/ng2-tools-page#82]
https://tools-stage.gapminderdev.org/tools/ 

ERROR TypeError: e.component.currentChart is undefined
Stackspårning:

![image](https://user-images.githubusercontent.com/3648190/31622819-bd636c2a-b29d-11e7-9153-7a41563dc7e8.png)

**Comment by buchslava** [comment]
@angieskazka how can I reproduce this case?

**Comment by angieskazka** [comment]
@buchslava 
open console. 
start the app with clean state https://tools-stage.gapminderdev.org/tools/
