### ISSUE TITLE
Back in browser doesn't restore the state

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/ng2-tools-page#98]
Steps to reproduce:
1. Open bubbles chart (or any)
2. Select a few countries
3. Press back button

Expect result:
Countries will be 'unselected' one by one by going back

Current result:
![selection_200](https://user-images.githubusercontent.com/18219232/31766908-d551bc70-b4d1-11e7-9223-9718d53a1c2d.png)

![ezgif com-video-to-gif 7](https://user-images.githubusercontent.com/18219232/31766890-cb7dc248-b4d1-11e7-9753-8b5a4648cfa2.gif)

**Comment by sergeyKhristenko** [comment]
Here is a nice example:
![ezgif com-video-to-gif 9](https://user-images.githubusercontent.com/18219232/31768730-57d731d2-b4d9-11e7-866c-23a72b7d6adc.gif)

**Comment by angieskazka** [comment]
yes, that's how it supposed to work. url changes but the event likely doesn't reach vizabi

**Comment by sergeyKhristenko** [comment]
The last state still doesn't get restored.
Maybe it's related to vizabi.
Place it here for now, just to make sure it doesn't get lost.

**Comment by angieskazka** [comment]
this is now a duplicate of #54
